{{/*
Expand the name of the chart.
*/}}
{{- define "mosquitto.name" -}}
{{- default .Chart.Name .Values.nameOverride | trunc 63 | trimSuffix "-" }}
{{- end }}

{{/*
Create a default fully qualified app name.
*/}}
{{- define "mosquitto.fullname" -}}
{{- if .Values.fullnameOverride }}
{{- .Values.fullnameOverride | trunc 63 | trimSuffix "-" }}
{{- else }}
{{- $name := default .Chart.Name .Values.nameOverride }}
{{- if contains $name .Release.Name }}
{{- .Release.Name | trunc 63 | trimSuffix "-" }}
{{- else }}
{{- printf "%s-%s" .Release.Name $name | trunc 63 | trimSuffix "-" }}
{{- end }}
{{- end }}
{{- end }}

{{/*
Create chart name and version as used by the chart label.
*/}}
{{- define "mosquitto.chart" -}}
{{- printf "%s-%s" .Chart.Name .Chart.Version | replace "+" "_" | trunc 63 | trimSuffix "-" }}
{{- end }}

{{/*
Common labels
*/}}
{{- define "mosquitto.labels" -}}
helm.sh/chart: {{ include "mosquitto.chart" . }}
{{ include "mosquitto.selectorLabels" . }}
{{- if .Chart.AppVersion }}
app.kubernetes.io/version: {{ .Chart.AppVersion | quote }}
{{- end }}
app.kubernetes.io/managed-by: {{ .Release.Service }}
app.kubernetes.io/part-of: mosquitto-mqtt
{{- with .Values.global.labels }}
{{ toYaml . }}
{{- end }}
{{- end }}

{{/*
Selector labels
*/}}
{{- define "mosquitto.selectorLabels" -}}
app.kubernetes.io/name: {{ include "mosquitto.name" . }}
app.kubernetes.io/instance: {{ .Release.Name }}
{{- end }}

{{/*
Create the name of the service account to use
*/}}
{{- define "mosquitto.serviceAccountName" -}}
{{- if .Values.serviceAccount.create }}
{{- default (include "mosquitto.fullname" .) .Values.serviceAccount.name }}
{{- else }}
{{- default "default" .Values.serviceAccount.name }}
{{- end }}
{{- end }}

{{/*
Get the namespace
*/}}
{{- define "mosquitto.namespace" -}}
{{- if .Values.global.namespace }}
{{- .Values.global.namespace }}
{{- else }}
{{- .Release.Namespace }}
{{- end }}
{{- end }}

{{/*
Apply resource preset configurations
Returns merged values with preset overrides
*/}}
{{- define "mosquitto.applyPreset" -}}
{{- $preset := .Values.resourcePreset -}}
{{- if and $preset (ne $preset "custom") -}}
{{- $presetConfig := index .Values.presets $preset -}}
{{- if $presetConfig -}}
{{- $_ := mergeOverwrite .Values $presetConfig -}}
{{- end -}}
{{- end -}}
{{- end -}}

{{/*
Get replica count (considers HA and preset)
*/}}
{{- define "mosquitto.replicaCount" -}}
{{- if .Values.highAvailability.enabled }}
{{- .Values.highAvailability.replicas }}
{{- else if eq .Values.resourcePreset "ha-cluster" }}
{{- 3 }}
{{- else }}
{{- .Values.replicaCount }}
{{- end }}
{{- end }}

{{/*
Get persistence size (considers preset)
*/}}
{{- define "mosquitto.persistenceSize" -}}
{{- $preset := .Values.resourcePreset -}}
{{- if and $preset (ne $preset "custom") -}}
{{- $presetConfig := index .Values.presets $preset -}}
{{- if $presetConfig -}}
{{- if $presetConfig.mqtt -}}
{{- if $presetConfig.mqtt.persistence -}}
{{- $presetConfig.mqtt.persistence.size -}}
{{- else -}}
{{- .Values.mqtt.persistence.size -}}
{{- end -}}
{{- else -}}
{{- .Values.mqtt.persistence.size -}}
{{- end -}}
{{- else -}}
{{- .Values.mqtt.persistence.size -}}
{{- end -}}
{{- else -}}
{{- .Values.mqtt.persistence.size -}}
{{- end -}}
{{- end }}

{{/*
Get max connections (considers preset)
*/}}
{{- define "mosquitto.maxConnections" -}}
{{- $preset := .Values.resourcePreset -}}
{{- if and $preset (ne $preset "custom") -}}
{{- $presetConfig := index .Values.presets $preset -}}
{{- if $presetConfig -}}
{{- if $presetConfig.mqtt -}}
{{- $presetConfig.mqtt.maxConnections -}}
{{- else -}}
{{- .Values.mqtt.maxConnections -}}
{{- end -}}
{{- else -}}
{{- .Values.mqtt.maxConnections -}}
{{- end -}}
{{- else -}}
{{- .Values.mqtt.maxConnections -}}
{{- end -}}
{{- end }}

{{/*
Get resource limits (considers preset)
*/}}
{{- define "mosquitto.resources" -}}
{{- $preset := .Values.resourcePreset -}}
{{- if and $preset (ne $preset "custom") -}}
{{- $presetConfig := index .Values.presets $preset -}}
{{- if $presetConfig -}}
{{- if $presetConfig.resources -}}
{{- toYaml $presetConfig.resources -}}
{{- else -}}
{{- toYaml .Values.resources -}}
{{- end -}}
{{- else -}}
{{- toYaml .Values.resources -}}
{{- end -}}
{{- else -}}
{{- toYaml .Values.resources -}}
{{- end -}}
{{- end }}

{{/*
Generate Mosquitto configuration file
*/}}
{{- define "mosquitto.config" -}}
# ============================================================================
# Mosquitto MQTT Broker Configuration
# Generated by Helm Chart - Fireball Industries
# "At least it's more reliable than Modbus over WiFi"
# ============================================================================

# Persistence configuration
persistence {{ .Values.mqtt.persistence.enabled }}
{{- if .Values.mqtt.persistence.enabled }}
persistence_location {{ .Values.mqtt.persistence.location }}
autosave_interval {{ .Values.mqtt.persistence.autosaveInterval }}
autosave_on_changes {{ .Values.mqtt.persistence.autosaveOnChanges }}
{{- end }}

# Connection limits
max_connections {{ include "mosquitto.maxConnections" . }}
max_queued_messages {{ .Values.mqtt.maxQueuedMessages }}
max_inflight_messages {{ .Values.mqtt.maxInflightMessages }}
max_qos {{ .Values.mqtt.maxQoS }}

# Message size
message_size_limit {{ .Values.mqtt.messageSize.max }}

# Logging
{{- if .Values.mqtt.logging.timestampFormat }}
log_timestamp_format %s
{{- else }}
log_timestamp_format %Y-%m-%dT%H:%M:%S
{{- end }}
{{- range .Values.mqtt.logging.types }}
log_type {{ . }}
{{- end }}
{{- if .Values.mqtt.logging.connectionLogs }}
connection_messages true
{{- else }}
connection_messages false
{{- end }}

# Protocol support
{{- if .Values.mqtt.protocol.mqtt5 }}
# MQTT 5.0 support enabled
{{- end }}

# Listeners
{{- if .Values.mqtt.ports.mqtt.enabled }}
# Plain MQTT
listener {{ .Values.mqtt.ports.mqtt.port }}
protocol mqtt
{{- if not .Values.mqtt.authentication.enabled }}
allow_anonymous {{ .Values.mqtt.authentication.allowAnonymous }}
{{- end }}
{{- end }}

{{- if .Values.mqtt.ports.mqtts.enabled }}
# MQTT over TLS/SSL
listener {{ .Values.mqtt.ports.mqtts.port }}
protocol mqtt
{{- if .Values.mqtt.tls.enabled }}
cafile /mosquitto/config/certs/ca.crt
certfile /mosquitto/config/certs/tls.crt
keyfile /mosquitto/config/certs/tls.key
tls_version {{ .Values.mqtt.tls.version }}
{{- if .Values.mqtt.tls.requireCertificate }}
require_certificate true
{{- end }}
{{- if .Values.mqtt.tls.ciphers }}
ciphers {{ .Values.mqtt.tls.ciphers }}
{{- end }}
{{- end }}
{{- end }}

{{- if .Values.mqtt.ports.websockets.enabled }}
# MQTT over WebSockets
listener {{ .Values.mqtt.ports.websockets.port }}
protocol websockets
{{- if not .Values.mqtt.authentication.enabled }}
allow_anonymous {{ .Values.mqtt.authentication.allowAnonymous }}
{{- end }}
{{- end }}

# Authentication
{{- if .Values.mqtt.authentication.enabled }}
allow_anonymous false
password_file /mosquitto/config/passwd
{{- end }}

# Access Control List
{{- if .Values.mqtt.acl.enabled }}
acl_file /mosquitto/config/acl.conf
{{- end }}

# Bridge connections
{{- if .Values.mqtt.bridge.enabled }}
{{- range .Values.mqtt.bridge.connections }}
connection {{ .name }}
address {{ .address }}
{{- range .topics }}
topic {{ . }}
{{- end }}
{{- if .clientId }}
clientid {{ .clientId }}
{{- end }}
{{- if .username }}
remote_username {{ .username }}
{{- end }}
{{- if .password }}
remote_password {{ .password }}
{{- end }}
cleansession {{ .cleanSession }}
{{- if .tryPrivate }}
try_private {{ .tryPrivate }}
{{- end }}
{{- if .tls }}
bridge_cafile /mosquitto/config/bridge-certs/ca.crt
bridge_certfile /mosquitto/config/bridge-certs/tls.crt
bridge_keyfile /mosquitto/config/bridge-certs/tls.key
{{- end }}
{{- end }}
{{- end }}

# Extra configuration
{{- if .Values.mqtt.extraConfig }}
{{ .Values.mqtt.extraConfig }}
{{- end }}
{{- end }}

{{/*
Generate ACL configuration
*/}}
{{- define "mosquitto.acl" -}}
{{- if .Values.mqtt.acl.enabled }}
{{- if .Values.mqtt.sparkplug.enabled }}
# Sparkplug B ACL Configuration
# Namespace: {{ .Values.mqtt.sparkplug.namespace }}

# Allow Sparkplug topics
{{- range .Values.mqtt.sparkplug.groupIds }}
# Group: {{ . }}
pattern readwrite {{ $.Values.mqtt.sparkplug.namespace }}/{{ . }}/#
{{- end }}

# State topics for birth/death certificates
pattern readwrite STATE/#

{{- end }}
{{- .Values.mqtt.acl.content }}
{{- end }}
{{- end }}

{{/*
Get MQTT service port
*/}}
{{- define "mosquitto.servicePort" -}}
{{- if .Values.mqtt.ports.mqtt.enabled }}
{{- .Values.mqtt.ports.mqtt.port }}
{{- else if .Values.mqtt.ports.mqtts.enabled }}
{{- .Values.mqtt.ports.mqtts.port }}
{{- else }}
1883
{{- end }}
{{- end }}

{{/*
Get service type
*/}}
{{- define "mosquitto.serviceType" -}}
{{- .Values.service.type | default "ClusterIP" }}
{{- end }}
